/*
 * openHAB REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommandDescription {
    #[serde(rename = "commandOptions", skip_serializing_if = "Option::is_none")]
    pub command_options: Option<Vec<models::CommandOption>>,
}

impl CommandDescription {
    pub fn new() -> CommandDescription {
        CommandDescription {
            command_options: None,
        }
    }
}

