/*
 * openHAB REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigurableServiceDto {
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "configDescriptionURI", skip_serializing_if = "Option::is_none")]
    pub config_description_uri: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "multiple", skip_serializing_if = "Option::is_none")]
    pub multiple: Option<bool>,
}

impl ConfigurableServiceDto {
    pub fn new() -> ConfigurableServiceDto {
        ConfigurableServiceDto {
            category: None,
            config_description_uri: None,
            id: None,
            label: None,
            multiple: None,
        }
    }
}

