/*
 * openHAB REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnrichedItemDto {
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "commandDescription", skip_serializing_if = "Option::is_none")]
    pub command_description: Option<Box<models::CommandDescription>>,
    #[serde(rename = "editable", skip_serializing_if = "Option::is_none")]
    pub editable: Option<bool>,
    #[serde(rename = "groupNames", skip_serializing_if = "Option::is_none")]
    pub group_names: Option<Vec<String>>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "link", skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(rename = "stateDescription", skip_serializing_if = "Option::is_none")]
    pub state_description: Option<Box<models::StateDescription>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "transformedState", skip_serializing_if = "Option::is_none")]
    pub transformed_state: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "unitSymbol", skip_serializing_if = "Option::is_none")]
    pub unit_symbol: Option<String>,
}

impl EnrichedItemDto {
    pub fn new() -> EnrichedItemDto {
        EnrichedItemDto {
            category: None,
            command_description: None,
            editable: None,
            group_names: None,
            label: None,
            link: None,
            metadata: None,
            name: None,
            state: None,
            state_description: None,
            tags: None,
            transformed_state: None,
            r#type: None,
            unit_symbol: None,
        }
    }
}
