/*
 * openHAB REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnrichedItemChannelLinkDto {
    #[serde(rename = "channelUID", skip_serializing_if = "Option::is_none")]
    pub channel_uid: Option<String>,
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "editable", skip_serializing_if = "Option::is_none")]
    pub editable: Option<bool>,
    #[serde(rename = "itemName", skip_serializing_if = "Option::is_none")]
    pub item_name: Option<String>,
}

impl EnrichedItemChannelLinkDto {
    pub fn new() -> EnrichedItemChannelLinkDto {
        EnrichedItemChannelLinkDto {
            channel_uid: None,
            configuration: None,
            editable: None,
            item_name: None,
        }
    }
}
