/*
 * openHAB REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FirmwareStatusDto {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "updatableVersion", skip_serializing_if = "Option::is_none")]
    pub updatable_version: Option<String>,
}

impl FirmwareStatusDto {
    pub fn new() -> FirmwareStatusDto {
        FirmwareStatusDto {
            status: None,
            updatable_version: None,
        }
    }
}

