/*
 * openHAB REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoggerBean {
    #[serde(rename = "loggers", skip_serializing_if = "Option::is_none")]
    pub loggers: Option<Vec<models::LoggerInfo>>,
}

impl LoggerBean {
    pub fn new() -> LoggerBean {
        LoggerBean {
            loggers: None,
        }
    }
}

