/*
 * openHAB REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoggerInfo {
    #[serde(rename = "level", skip_serializing_if = "Option::is_none")]
    pub level: Option<String>,
    #[serde(rename = "loggerName", skip_serializing_if = "Option::is_none")]
    pub logger_name: Option<String>,
}

impl LoggerInfo {
    pub fn new() -> LoggerInfo {
        LoggerInfo {
            level: None,
            logger_name: None,
        }
    }
}

