/*
 * openHAB REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MappingDto {
    #[serde(rename = "column", skip_serializing_if = "Option::is_none")]
    pub column: Option<i32>,
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "releaseCommand", skip_serializing_if = "Option::is_none")]
    pub release_command: Option<String>,
    #[serde(rename = "row", skip_serializing_if = "Option::is_none")]
    pub row: Option<i32>,
}

impl MappingDto {
    pub fn new() -> MappingDto {
        MappingDto {
            column: None,
            command: None,
            icon: None,
            label: None,
            release_command: None,
            row: None,
        }
    }
}
