/*
 * openHAB REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersistenceServiceConfigurationDto {
    #[serde(rename = "configs", skip_serializing_if = "Option::is_none")]
    pub configs: Option<Vec<models::PersistenceItemConfigurationDto>>,
    #[serde(rename = "cronStrategies", skip_serializing_if = "Option::is_none")]
    pub cron_strategies: Option<Vec<models::PersistenceCronStrategyDto>>,
    #[serde(rename = "defaults", skip_serializing_if = "Option::is_none")]
    pub defaults: Option<Vec<String>>,
    #[serde(rename = "editable", skip_serializing_if = "Option::is_none")]
    pub editable: Option<bool>,
    #[serde(rename = "equalsFilters", skip_serializing_if = "Option::is_none")]
    pub equals_filters: Option<Vec<models::PersistenceFilterDto>>,
    #[serde(rename = "includeFilters", skip_serializing_if = "Option::is_none")]
    pub include_filters: Option<Vec<models::PersistenceFilterDto>>,
    #[serde(rename = "serviceId", skip_serializing_if = "Option::is_none")]
    pub service_id: Option<String>,
    #[serde(rename = "thresholdFilters", skip_serializing_if = "Option::is_none")]
    pub threshold_filters: Option<Vec<models::PersistenceFilterDto>>,
    #[serde(rename = "timeFilters", skip_serializing_if = "Option::is_none")]
    pub time_filters: Option<Vec<models::PersistenceFilterDto>>,
}

impl PersistenceServiceConfigurationDto {
    pub fn new() -> PersistenceServiceConfigurationDto {
        PersistenceServiceConfigurationDto {
            configs: None,
            cron_strategies: None,
            defaults: None,
            editable: None,
            equals_filters: None,
            include_filters: None,
            service_id: None,
            threshold_filters: None,
            time_filters: None,
        }
    }
}
