/*
 * openHAB REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RootBean {
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<models::Links>>,
    #[serde(rename = "locale", skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
    #[serde(rename = "measurementSystem", skip_serializing_if = "Option::is_none")]
    pub measurement_system: Option<String>,
    #[serde(rename = "runtimeInfo", skip_serializing_if = "Option::is_none")]
    pub runtime_info: Option<Box<models::RuntimeInfo>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl RootBean {
    pub fn new() -> RootBean {
        RootBean {
            links: None,
            locale: None,
            measurement_system: None,
            runtime_info: None,
            version: None,
        }
    }
}

