/*
 * openHAB REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RuntimeInfo {
    #[serde(rename = "buildString", skip_serializing_if = "Option::is_none")]
    pub build_string: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl RuntimeInfo {
    pub fn new() -> RuntimeInfo {
        RuntimeInfo {
            build_string: None,
            version: None,
        }
    }
}
