/*
 * openHAB REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemInfoBean {
    #[serde(rename = "systemInfo", skip_serializing_if = "Option::is_none")]
    pub system_info: Option<Box<models::SystemInfo>>,
}

impl SystemInfoBean {
    pub fn new() -> SystemInfoBean {
        SystemInfoBean { system_info: None }
    }
}
