/*
 * openHAB REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemInfo {
    #[serde(
        rename = "availableProcessors",
        skip_serializing_if = "Option::is_none"
    )]
    pub available_processors: Option<i32>,
    #[serde(rename = "configFolder", skip_serializing_if = "Option::is_none")]
    pub config_folder: Option<String>,
    #[serde(rename = "freeMemory", skip_serializing_if = "Option::is_none")]
    pub free_memory: Option<i64>,
    #[serde(rename = "javaVendor", skip_serializing_if = "Option::is_none")]
    pub java_vendor: Option<String>,
    #[serde(rename = "javaVendorVersion", skip_serializing_if = "Option::is_none")]
    pub java_vendor_version: Option<String>,
    #[serde(rename = "javaVersion", skip_serializing_if = "Option::is_none")]
    pub java_version: Option<String>,
    #[serde(rename = "logFolder", skip_serializing_if = "Option::is_none")]
    pub log_folder: Option<String>,
    #[serde(rename = "osArchitecture", skip_serializing_if = "Option::is_none")]
    pub os_architecture: Option<String>,
    #[serde(rename = "osName", skip_serializing_if = "Option::is_none")]
    pub os_name: Option<String>,
    #[serde(rename = "osVersion", skip_serializing_if = "Option::is_none")]
    pub os_version: Option<String>,
    #[serde(rename = "startLevel", skip_serializing_if = "Option::is_none")]
    pub start_level: Option<i32>,
    #[serde(rename = "totalMemory", skip_serializing_if = "Option::is_none")]
    pub total_memory: Option<i64>,
    #[serde(rename = "uptime", skip_serializing_if = "Option::is_none")]
    pub uptime: Option<i64>,
    #[serde(rename = "userdataFolder", skip_serializing_if = "Option::is_none")]
    pub userdata_folder: Option<String>,
}

impl SystemInfo {
    pub fn new() -> SystemInfo {
        SystemInfo {
            available_processors: None,
            config_folder: None,
            free_memory: None,
            java_vendor: None,
            java_vendor_version: None,
            java_version: None,
            log_folder: None,
            os_architecture: None,
            os_name: None,
            os_version: None,
            start_level: None,
            total_memory: None,
            uptime: None,
            userdata_folder: None,
        }
    }
}
