/*
 * openHAB REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThingActionDto {
    #[serde(rename = "actionUid", skip_serializing_if = "Option::is_none")]
    pub action_uid: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "inputConfigDescriptions", skip_serializing_if = "Option::is_none")]
    pub input_config_descriptions: Option<Vec<models::ConfigDescriptionParameterDto>>,
    #[serde(rename = "inputs", skip_serializing_if = "Option::is_none")]
    pub inputs: Option<Vec<models::Input>>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "outputs", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Vec<models::Output>>,
    #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
    pub visibility: Option<Visibility>,
}

impl ThingActionDto {
    pub fn new() -> ThingActionDto {
        ThingActionDto {
            action_uid: None,
            description: None,
            input_config_descriptions: None,
            inputs: None,
            label: None,
            outputs: None,
            visibility: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Visibility {
    #[serde(rename = "VISIBLE")]
    Visible,
    #[serde(rename = "HIDDEN")]
    Hidden,
    #[serde(rename = "EXPERT")]
    Expert,
}

impl Default for Visibility {
    fn default() -> Visibility {
        Self::Visible
    }
}

