/*
 * openHAB REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UoMInfoBean {
    #[serde(rename = "uomInfo", skip_serializing_if = "Option::is_none")]
    pub uom_info: Option<Box<models::UoMInfo>>,
}

impl UoMInfoBean {
    pub fn new() -> UoMInfoBean {
        UoMInfoBean { uom_info: None }
    }
}
