name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: davidB/rust-cargo-make@v1
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Run CI
      run: cargo make ci-flow
